### ISSUE TITLE
can you share some data file to test how it works

### ISSUE THREAD

**Issue by Sandy4321** [canoalberto/ur-CAIM#1]
great code thanks
only
1
can you share some data file to test how it works , to compare my calculation results with your calculation results  to make sure I use it in correct way
2
may be know somebody else implementation not using weka , but only plain java code?

**Comment by canoalberto** [comment]
- Added data/iris.arff as the classic dataset to test the implementation. You can use any ARFF dataset from UCI/KEEL/etc
- Added runnable/urCAIM.java to run the code calling the Weka API but without needing the Weka GUI. This way it's easier to run batch experiments and compare it with other existing discretizers.

**Comment by Sandy4321** [comment]
great thanks
Added data/iris.arff as the classic dataset to test the implementation. You can use any ARFF dataset from UCI/KEEL/etc
also it would be great to share data after descritization 
to able us to check if run your code correctly ?
