### ISSUE TITLE
BUT DO  HAVE IT IN PYTHON ?

### ISSUE THREAD

**Issue by Sandy4321** [canoalberto/ur-CAIM#2]
GREAT ALGORITHM
BUT DO  HAVE IT IN PYTHON ?

**Comment by canoalberto** [comment]
No, but you can recode it on python easily

**Comment by Sandy4321** [comment]
YES IT WOULD BE VERY KIND OF YOU
SINCE VAST MAJORITY USE PYTHON NOW DAYS ...
THANK YOU VERY MUCH IN ADVANCE...
