### ISSUE TITLE
may you pls help to find what data sets where used since link from paper is broken 

### ISSUE THREAD

**Issue by Sandy4321** [canoalberto/ur-CAIM#3]
may you pls help to find what data sets where used since link from paper is broken 
since
link from paper page 7 
https://helvia.uco.es/xmlui/bitstream/handle/10396/13003/article.pdf?sequence=1&isAllowed=y
 is broken 
The data sets description along with their partitions, the ur-CAIM
source code and WEKA plugin, the experimental settings and results
for all data sets and algorithms are fully described and publicly
available to facilitate the replicability of the experiments and future
comparisons at the website:
http://www.uco.es/grupos/kdis/wiki/ur-CAIM

![image](https://user-images.githubusercontent.com/11426119/148566973-32b818d9-f917-46ac-8baf-a5146f3980f9.png)

**Comment by canoalberto** [comment]
I no longer have access to that server but I was able to restore a backup at https://people.vcu.edu/~acano/ur-CAIM/

**Comment by Sandy4321** [comment]
great
thank 
very kind of you to help
